---
title: "Sentiment Analysis on Youtube Comments"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Loading the data 



```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)

# Read the data from the CSV file
df <- read.csv("/Users/tarikajain/Desktop/Marketing/subset_comments_analysis.csv")
head(df)
str(df)
summary (df)
```


```{r}

df$published_at <- as.POSIXct(df$published_at, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")

# Launch of ChatGPT as cutoff date
cut_off_date <- as.Date("2022-11-30")


df <- df %>%
  mutate(
    period = factor(if_else(published_at <= cut_off_date, "Before", "After"), 
                    levels = c("Before", "After"))
  )

# Filtering the dataset to exclude '3Blue1Brown' and 'Siraj Raval' channels, and for non-NA polarized scores
df_filtered <- df %>%
  filter(!channel_name %in% c('3Blue1Brown', 'Siraj Raval'), !is.na(polarized_score))

# Excluding NAs from the period variable
df_filtered <- df_filtered %>%
  filter(!is.na(period))

# Plot 
ggplot(df_filtered, aes(x = period, y = polarized_score, fill = period)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape = 20, size = 3, color = "darkred") +
  facet_wrap(~ channel_name, scales = "free_y") +
  theme_minimal() +
  labs(title = "Distribution of Sentiment Scores by Channel and Period",
       x = "",
       y = "Polarized Score") +
  scale_fill_manual(values = c("Before" = "#f9d448", "After" = "#7ca655")) +
  theme(legend.position = "none")

```

